meta_product_name: "Recipeper"
meta_title: "Recipeper - Cook enough and not too much"
meta_description: "Relevant description"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
# <span>Photo by <a href="https://unsplash.com/@alyson_jane?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Alyson McPhee</a> on <a href="https://unsplash.com/s/photos/cooking?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>
